import {
  File,
  HelpCircle,
  PanelLeftOpen,
  PanelLeftClose,
  LayoutDashboard,
  List,
  User,
  Kanban,
  ChartGantt,
  ChartNetwork,
  Brain,
  Settings,
  Menu,
  Calendar,
  LayoutGrid,
  ArrowRight,
  ChevronDown,
  Check,
  Eye,
  EyeOff,
  LucideIconData,
  AppWindow,
  Funnel,
  Notebook,
  Target,
  Clock,
  Link,
  Tags,
  Ellipsis,
  Plus,
  ChevronUp,
  Pencil,
  BookOpen,
  Trash,
  CopyPlus,
  Pin,
  PinOff,
  Flame,
  Lightbulb,
  CircleDashed,
  Circle,
  CircleCheck,
  Loader,
  Archive,
  ChevronLeft,
  Zap,
  RotateCcw,
  ArchiveRestore,
  Shredder,
  MessageCircleMore,
  X,
  ArrowLeft,
  SquarePen,
  ChevronRight,
  Columns2,
  Grid2x2,
  Grid3x3,
  CalendarRange,
  Building2,
  ChevronsLeft,
  ChevronsRight,
  ArrowDown,
  ArrowUp,
} from 'lucide-angular';

export const ICONS = [
  { name: 'File', icon: File },
  { name: 'HelpCircle', icon: HelpCircle },
  { name: 'User', icon: User },
  { name: 'PanelLeftOpen', icon: PanelLeftOpen },
  { name: 'PanelLeftClose', icon: PanelLeftClose },
  { name: 'LayoutDashboard', icon: LayoutDashboard },
  { name: 'List', icon: List },
  { name: 'Kanban', icon: Kanban },
  { name: 'Calendar', icon: Calendar },
  { name: 'ChartGantt', icon: ChartGantt },
  { name: 'ChartNetwork', icon: ChartNetwork },
  { name: 'LayoutGrid', icon: LayoutGrid },
  { name: 'Brain', icon: Brain },
  { name: 'Settings', icon: Settings },
  { name: 'Menu', icon: Menu },
  { name: 'ArrowRight', icon: ArrowRight },
  { name: 'ChevronDown', icon: ChevronDown },
  { name: 'Check', icon: Check },
  { name: 'Eye', icon: Eye },
  { name: 'EyeOff', icon: EyeOff },
  { name: 'AppWindow', icon: AppWindow },
  { name: 'Funnel', icon: Funnel },
  { name: 'Notebook', icon: Notebook },
  { name: 'Pencil', icon: Pencil },
  { name: 'Target', icon: Target },
  { name: 'Clock', icon: Clock },
  { name: 'Link', icon: Link },
  { name: 'Tags', icon: Tags },
  { name: 'Ellipsis', icon: Ellipsis },
  { name: 'Plus', icon: Plus },
  { name: 'ChevronUp', icon: ChevronUp },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Trash', icon: Trash },
  { name: 'CopyPlus', icon: CopyPlus },
  { name: 'Pin', icon: Pin },
  { name: 'PinOff', icon: PinOff },
  { name: 'Flame', icon: Flame },
  { name: 'LightBulb', icon: Lightbulb },
  { name: 'CircleDashed', icon: CircleDashed },
  { name: 'Circle', icon: Circle },
  { name: 'CircleCheck', icon: CircleCheck },
  { name: 'Loader', icon: Loader },
  { name: 'Archive', icon: Archive },
  { name: 'ChevronLeft', icon: ChevronLeft },
  { name: 'Zap', icon: Zap },
  { name: 'RotateCcw', icon: RotateCcw },
  { name: 'ArchiveRestore', icon: ArchiveRestore },
  { name: 'Shredder', icon: Shredder },
  { name: 'MessageCircleMore', icon: MessageCircleMore },
  { name: 'X', icon: X },
  { name: 'ArrowLeft', icon: ArrowLeft },
  { name: 'SquarePen', icon: SquarePen },
  { name: 'ChevronRight', icon: ChevronRight },
  { name: 'Columns2', icon: Columns2 },
  { name: 'Grid2x2', icon: Grid2x2 },
  { name: 'Grid3x3', icon: Grid3x3 },
  { name: 'CalendarRange', icon: CalendarRange },
  { name: 'Building2', icon: Building2 },
  { name: 'ChevronsLeft', icon: ChevronsLeft },
  { name: 'ChevronsRight', icon: ChevronsRight },
  { name: 'ArrowDown', icon: ArrowDown },
  { name: 'ArrowUp', icon: ArrowUp },
];

export const LUCIDE_ICONS = ICONS.reduce((acc, cur) => {
  acc[cur.name] = cur.icon;
  return acc;
}, {} as Record<string, LucideIconData>);
